<?php

namespace JobZBundle\Repository;

use JobZBundle\Entity\Category;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $amount
     * @return array
     */
    public function findLatest($amount = 1)
    {
        $qb = $this->getQueryBuilder()->orderBy('j.id', 'asc')
            ->setMaxResults($amount);
        return $qb->getQuery()->getResult();
    }

    private function getQueryBuilder()
    {
        $em = $this->getEntityManager();

        $qb = $em->getRepository('JobZBundle:Job')
            ->createQueryBuilder('j');

        return $qb;
    }
}
