fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

job_z:
    resource: "@JobZBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
