job_z_info:
    resource: "@JobZBundle/Controller/InfoController.php"
    type:     annotation

job_z_category:
    resource: "@JobZBundle/Controller/CategoryController.php"
    type:     annotation

job_z_job:
    resource: "@JobZBundle/Controller/JobController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

job_z:
    resource: "@JobZBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
